### PR TITLE
Plumb source text through task graph registration.

### PR DESCRIPTION
**Pull request by thetorpedodog**

### CODE REVIEW

**Review by snagles — APPROVED** [review]

**Comment by thetorpedodog** [comment]
All the test failures are server-side flakes. Submitting.

**Comment by thetorpedodog** [comment]
All the test failures are server-side flakes. Submitting.

**Comment by Shelnutt2** [comment]
It looks like this got merged before CI finished. I've updated the repo settings to require all CI checks to pass.

**Comment by thetorpedodog** [comment]
Yes, this is correct and intentional. All the failures were due to transient server-side flakes rather than genuine bugs introduced.

**Pull request merged**
