### PR TITLE
add import to init

### PR DESCRIPTION
**Pull request by spencerseale**
This is to correct the code so the docs: https://docs.tiledb.com/cloud/api-reference/utilities#listing-tasks are correct

https://app.shortcut.com/tiledb-inc/story/51947/correctly-import-tasks-function

### CODE REVIEW

**Comment by spencerseale** [comment]
The alternative is to change the docs and not the code, not sure what we'd want to do here. @kounelisagis @nickvigilante

**Comment by nickvigilante** [comment]
@spencerseale I'm generally in favor of changing docs before changing code, unless this particular code change makes the product more usable and less buggy for our end users, in which case we should do it. Docs are easy to change, but unless it's a customer request or an emergency, I'm really only updating GitHub as opposed to GitBook.

**Comment by kounelisagis** [comment]
> @nickvigilante Makes sense, I just see that we import other functions into that same level from that method such as `task`, so assumed we would also want to import `tasks`. Would like to also see what Agis would like to do and can proceed that way.

Spencer's argument seems logical to me. The way it works, as shown in the documentation, feels better for the user. Let's make that change.

**Review by kounelisagis — APPROVED** [review]

**Review by nickvigilante — APPROVED** [review]
I'll approve then as well. Thanks for this change!

**Comment by spencerseale** [comment]
@kounelisagis the unit tests are alerting of some unfortunate collisions in a function named `tasks` being located in a module named `tiledb.cloud.tasks`. 

We need to either rename the function or the module to make this cleaner.

Renaming the module would probably be harder to track down all the breaks this would cause. If you are still down to allow the tasks function to be imported into `tiledb.cloud`, what should I rename it as and can you think of any other issues this would cause?

**Comment by JohnMoutafis** [comment]
@spencerseale Indeed the test issue is coming from an import collision between the `tasks` module and the `tasks` function that is now explicitly imported as `tiledb.cloud.tasks`.

- Since the `tasks` function just returns a sequence of tasks it would make sense to rename it to `fetch_tasks`, `task_list` or `all_tasks` and leave the module name as is.
- Another option that will solve the issue for now (but it has the potential to reemerge)  would be to:

      from .tasks import tasks as fetch_tasks
      
      ...
      __all__ = (
         ...
         fetch_tasks
         ...
      )
  and update the docs to match (`all_tasks = tiledb.cloud.fetch_tasks()`)

**Comment by spencerseale** [comment]
@JohnMoutafis since we use 'fetch' elsewhere i'll change the function to `fetch_tasks`. Can you think of elsewhere I should look for any breaks? Thank you for your input and I apologize for not including you initially.

**Comment by spencerseale** [comment]
@nickvigilante can we update: https://docs.tiledb.com/cloud/api-reference/utilities#listing-tasks to `tiledb.cloud.fetch_tasks`? idk if we have any other docs for this, that's all I can find..

**Comment by Shelnutt2** [comment]
We need to be careful about backwards API compatibility. This is a breaking change and as we saw with the `files` rename it is likely to directly impact some users. Are there alternatives we can consider to maintain compatibility?

**Comment by spencerseale** [comment]
@Shelnutt2 see latest commit and let me know if that's sufficient. Otherwise we can scrap this PR and update docs, it just feels funny with some functions imported into `tiledb.cloud` from that module and others not.

This passes:

```python
import tiledb.cloud
import datetime

ago = datetime.datetime.utcnow() - datetime.timedelta(days=35)

old = tiledb.cloud.tasks.tasks(namespace="spencerseale", start=ago)
new = tiledb.cloud.fetch_tasks(namespace="spencerseale", start=ago)

assert old == new
```

My proposition is to include this to support backwards compat and change all docs to specify `tiledb.cloud.fetch_results`

**Comment by spencerseale** [comment]
Another thing, one of the examples listed in the [docs](https://docs.tiledb.com/cloud/api-reference/utilities#listing-tasks:~:text=array_tasks%20%3D%20tiledb.cloud.tasks(array%3D%22tiledb%3A//TileDB%2DInc/quickstart_sparse%22)) doesn't work even when I call it with correct module tree: 

`array_tasks = tiledb.cloud.tasks.tasks(array="tiledb://TileDB-Inc/quickstart_sparse")`

```
TileDBCloudError                          Traceback (most recent call last)
Input In [1], in <cell line: 2>()
      1 import tiledb.cloud
----> 2 array_tasks = tiledb.cloud.tasks.tasks(array="tiledb://TileDB-Inc/quickstart_sparse")

File /opt/conda/lib/python3.9/site-packages/tiledb/cloud/tasks.py:108, in tasks(namespace, array, start, end, status, page, per_page, async_req)
    105     return api_instance.tasks_get(**args)
    107 except GenApiException as exc:
--> 108     raise tiledb_cloud_error.maybe_wrap(exc) from None

TileDBCloudError: Namespace not found - Code: 25 - Extra details: {'request_id': '3fc7fc5c-dc27-4f86-8a08-66d20a35ec50'}
```

**Review by JohnMoutafis — APPROVED** [review]

**Comment by Shelnutt2** [comment]
> @Shelnutt2 see latest commit and let me know if that's sufficient. Otherwise we can scrap this PR and update docs, it just feels funny with some functions imported into `tiledb.cloud` from that module and others not.
> 
> This passes:
> 
> ```python
> import tiledb.cloud
> import datetime
> 
> ago = datetime.datetime.utcnow() - datetime.timedelta(days=35)
> 
> old = tiledb.cloud.tasks.tasks(namespace="spencerseale", start=ago)
> new = tiledb.cloud.fetch_tasks(namespace="spencerseale", start=ago)
> 
> assert old == new
> ```
> 
> Including this change will ensure backwards compatibility while we change all docs to specify `tiledb.cloud.fetch_results`

Thanks, I think this is good!

**Comment by spencerseale** [comment]
@JohnMoutafis i'll open a shortcut for that and merge this. It's mainly just the `arrays` arg that's not working.

**Comment by JohnMoutafis** [comment]
Thank you @spencerseale

**Comment by spencerseale** [comment]
@nickvigilante I'm merging and we have backwards compatibility maintained. Can you update the originally linked docs so any current reference `tiledb.cloud.tasks` is changed to `tiledb.cloud.fetch_tasks`. Thank you!

**Pull request merged**
