### PR TITLE
Pin to Python 3.7.16 on Mac OS due to GitHub Actions breakage.

### PR DESCRIPTION
**Pull request by thetorpedodog**
Due to this issue:
https://github.com/actions/setup-python/issues/682
Python 3.7 does not work on Mac OS. Instead we manually seed the matrix with the right Python version for each OS.

### CODE REVIEW

**Review by ihnorton — DISMISSED** [review]
LGTM (when green). Thanks!

**Comment by thetorpedodog** [comment]
Re-requesting a review because I reworked how we pick what version to install.

**Comment by thetorpedodog** [comment]
cool how it shows that i pushed the branch but does not seem to be updating the view here

**Comment by thetorpedodog** [comment]
finally got github to pick up that a change was made. failures are unrelated (and extremely confusing).

**Comment by thetorpedodog** [comment]
Actually this has been obsoleted! Apparently GitHub pushed a working version of 3.7.17.

**Pull request closed without merging**
