### PR TITLE
Build documentation using existing Sphinx setup.

### PR DESCRIPTION
**Pull request by thetorpedodog**
This uses the infrastructure we have for Sphinx to generate and build a GitHub Pages website with our docs. Based on:

https://coderefinery.github.io/documentation/gh_workflow/#exercise-deploy-sphinx-documentation-to-github-pages

### CODE REVIEW

**Review by Shelnutt2 — CHANGES_REQUESTED** [review]
Please migrate this to quarto/quartodoc.

**Comment by JohnMoutafis** [comment]
@thetorpedodog @Shelnutt2 is this still relevant to CLoud-Py?

**Comment by JohnMoutafis** [comment]
Can be closed after finalization and merging of: https://github.com/TileDB-Inc/TileDB-Cloud-Py/pull/579

**Comment by JohnMoutafis** [comment]
Closing as https://github.com/TileDB-Inc/TileDB-Cloud-Py/pull/579 introduces Quarto documentation.

**Pull request closed without merging**
