### PR TITLE
Update API usage to fix generic UDF registration (UDFRegistration->UDFInfoUpdate)

### PR DESCRIPTION
**Pull request by ihnorton**

### CODE REVIEW

**Comment by ihnorton** [comment]
This fixes `tiledb.cloud.register_generic_udf`, which was broken with the error:
```
```

With the change, I can run this (`ihnorton/test1` is identity function):
```
In [15]: tiledb.cloud.udf.exec("helo", name="ihnorton/test1")
Out[15]: 'helo'
```

But the query functionality doesn't seem to work:
```
In [16]: udf.info(name="ihnorton/test1")
---------------------------------------------------------------------------
TileDBCloudError                          Traceback (most recent call last)
<ipython-input-16-dd256f74b4d0> in <module>
----> 1 udf.info(name="ihnorton/test1")

~/work/git/TileDB-Cloud-Py/tiledb/cloud/udf.py in info(name)
    401         return api_instance.get_udf_info(namespace=namespace, name=name)
    402     except GenApiException as exc:
--> 403         raise tiledb_cloud_error.check_exc(exc) from None
    404
    405

TileDBCloudError: Array or Namespace Not found

In [17]: udf.list_registered_udfs(namespace="ihnorton")
Out[17]:
{'pagination_metadata': {'page': None,
                         'per_page': None,
                         'total_items': None,
                         'total_pages': None},
 'udf_info_list': None}
```

**Comment by ihnorton** [comment]
I've started adding a simple test for `udf.register_generic_udf`, however I expect it will fail because `exec` doesn't default to a user-specific namespace (requires `name="namespace/func"`; `name="func"` fails).

**Review by Shelnutt2 — APPROVED** [review]
Thanks for the fixes!

**Comment by ihnorton** [comment]
This was done in #95 (+#96), however there is a test here too so rebased to try CI again.

**Comment by Shelnutt2** [comment]
No longer needed

**Pull request closed without merging**
